# .github/workflows/on-merge-main.yml

name: On PR Merge to Main

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo PR info and repo name
        run: |
          echo "✅ PR #${{ github.event.pull_request.number }} was merged into main"
          echo "Title: ${{ github.event.pull_request.title }}"
          echo "Author: ${{ github.event.pull_request.user.login }}"
          echo "Repo: ${{ github.repository }}"
