# .github/workflows/on-merge-main.yml

name: On PR Merge to Main

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout cod
        uses: actions/checkout@v3

      - name: Echo PR info and repo name
        run: |
          REPO_FULL="${{ github.repository }}"
          REPO_NAME="${REPO_FULL##*/}"  # extracts the part after the last /
          
          echo "✅ PR #${{ github.event.pull_request.number }} was merged into main"
          echo "Title: ${{ github.event.pull_request.title }}"
          echo "Author: ${{ github.event.pull_request.user.login }}"
          echo "Repo: $REPO_NAME"
          
          curl https://raw.githubusercontent.com/saai-sudarsanan-swym/skyra-docs/refs/heads/main/feature_doc.md -o feature_doc.md
          curl https://raw.githubusercontent.com/saai-sudarsanan-swym/skyra-docs/refs/heads/main/design_doc.md -o design_doc.md
          
          curl -X POST https://radically-sharing-platypus.ngrok-free.app/generate \
            -H "Content-Type: multipart/form-data" \
            -F "feature_doc=@./feature_doc.md" \
            -F "design_doc=@./design_doc.md" \
            -F "data={\"repo\": \"$REPO_NAME\", \"pr_number\": \"${{ github.event.pull_request.number }}\"}"