# .github/workflows/on-merge-main.yml

name: On PR Merge to Main

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout cod
        uses: actions/checkout@v3

      - name: Echo PR info and repo name
        run: |
          REPO_FULL="${{ github.repository }}"
          REPO_NAME="${REPO_FULL##*/}"  # extracts the part after the last /
          
          echo "✅ PR #${{ github.event.pull_request.number }} was merged into main"
          echo "Title: ${{ github.event.pull_request.title }}"
          echo "Author: ${{ github.event.pull_request.user.login }}"
          echo "Repo: $REPO_NAME"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          FILE_NAME=$(date +%Y%m%d%H%M%S)_change_${REPO_NAME}_${PR_NUMBER}.md
          
          curl https://raw.githubusercontent.com/saai-sudarsanan-swym/skyra-docs/refs/heads/main/feature_doc.md -o feature_doc.md
          curl https://raw.githubusercontent.com/saai-sudarsanan-swym/skyra-docs/refs/heads/main/design_doc.md -o design_doc.md
          
          curl -X POST https://radically-sharing-platypus.ngrok-free.app/generate \
            -H "Content-Type: multipart/form-data" \
            -F "feature_doc=@./feature_doc.md" \
            -F "design_doc=@./design_doc.md" \
            -F "data={\"repo\": \"$REPO_NAME\", \"pr_number\": \"${{ github.event.pull_request.number }}\"}" -o ./changelog/src/${FILE_NAME}

          echo "Changelog file name: $FILE_NAME"

          echo "- [$(date +%Y%m%d%H%M%S)_change_${REPO_NAME}_${PR_NUMBER}](./${FILE_NAME})" >> ./changelog/src/SUMMARY.md

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.10'
      
      - run: mdbook build ./changelog --dest-dir ./changelog/book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./changelog/book